blog/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ArticleView.as_view(), name='article'),
    path('<int:pk>/new_comment', views.NewComment.as_view(), name='new_comment'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('signup/', views.SignUp.as_view(), name='signup'),
]

django_lesson/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from markdown import markdown
from django.contrib.auth.models import User


class Article(models.Model):
    header = models.CharField(max_length=128)
    markdown = models.TextField()
    pub_date = models.DateTimeField('date published')

    def save(self, **kwargs):
        self.html = markdown(self.markdown)
        super(Article, self).save()

    def __str__(self):
        return self.header

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'pk': self.pk})


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    likes = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'pk': self.article.pk})

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            })
        }

blog/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import CreateView

from blog.forms import CommentForm
from blog.models import Article, Comment


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_articles_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Article.objects.order_by('-pub_date')[:5]


class ArticleView(generic.DetailView):
    model = Article
    template_name = 'article.html'


class NewComment(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'new_comment_form.html'
    login_url = reverse_lazy('blog:login')
    redirect_field_name = REDIRECT_FIELD_NAME

    def form_valid(self, form):
        form.instance.article = get_object_or_404(Article, *self.args, **self.kwargs)
        return super(NewComment, self).form_valid(form)


class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        self.object = form.save()
        login(self.request, self.object)
        return HttpResponseRedirect(self.get_success_url())

polls/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Question

def index(request):
    template = loader.get_template("polls/index.html")
    context = {
        'items': Question.objects.order_by("-pub_date")[:5],
    }
    return HttpResponse(template.render(context, request))




blog/templates/article.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">

        <div class="row">

            <!-- Post Content Column -->
            <div class="col-lg-12">

                <!-- Title -->
                <h1 class="mt-4">{{ article.header }}</h1>

                <!-- Date/Time -->
                <p>Posted on {{ article.pub_date }}</p>

                <hr>

                {{ article.markdown|safe }}

                <hr>

                <!-- Comments Form -->
                <div class="card my-4">
                    <div class="card-body">
                        <a href="{% url 'blog:new_comment' article.id %}" class="btn btn-primary">Leave a Comment
                            &rarr;</a>
                    </div>
                </div>

                <ul>
                    {% for comment in article.comment_set.all %}
                        <li>
                            <div class="media mb-4">
                                <div class="media-body">
                                    {{ comment.text }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- /.row -->

    </div>
{% endblock %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Мой блог</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap-grid.min.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap-reboot.min.css" %}">
    <link rel="stylesheet" href="{% static "index.css" %}">

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Лучший блог</a>

    <div>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link">Hello, {{ user }}</a>
                {% else %}
                    <a class="nav-link">Hello, unknown dude</a>
                {% endif %}
            </li>
        </ul>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "blog:logout" %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "blog:login" %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "blog:signup" %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main>
    {% block content %}
    {% endblock %}
</main>

<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src={% static "jquery/jquery-3.4.1.min.js" %}></script>
<script src={% static "bootstrap/js/bootstrap.bundle.min.js" %}></script>

</body>

</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">

            <h1 class="my-4">Статьи
            </h1>

            {% for article in latest_articles_list %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{article.header}}</h2>
                        <p>{{ article.pub_date }}</p>
                        <p class="card-text">{{article.markup|safe}}</p>
                        <a href="{% url 'blog:article' article.id %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/new_comment_form.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <form method="POST" class="post-form">{% csrf_token %}
            <div class="form-group">
                {{ form }}
            </div>
            <button type="submit" class="save btn btn-primary">Send</button>
        </form>
    </div>

{% endblock %}

polls/templates/polls/index.html
{% if items %}
    <ul>
    {% for item in items %}
        <li>{{ item.question_text }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>There is no comments.</p>
{% endif %}